checks:
  php:
    avoid_closing_tag: false
    avoid_superglobals: false
    coding_standard:
      name: WordPress
    no_exit: false
    no_global_keyword: false
    one_class_per_file: false
    psr2_class_declaration: false
    psr2_control_structure_declaration: false
    psr2_switch_declaration: false
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
    
filter:
    excluded_paths:
        - 'bin/*'
        - 'docs/*'
        - 'node_modules/*'
        - 'tests/*'
        - 'vendor/*/tests/*'
        - '*.min.js'
        - '*.min.css'
        - 'assets/js/vendor/*'
        - 'Gulpfile.js'
    dependency_paths:
        - 'wordpress/'
        - 'vendor/'
tools:
    php_code_sniffer:
        config:
            standard: WordPress
build:
    environment:
      node: 'v18.1.0'
      php: '8.0'
      mysql: true
      apache2:
        modules:
          - rewrite
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            tests:
                override:
                    - php-scrutinizer-run
